Repository lfglabs-dev/app.starknet.id, pull requests merged in 2023-11, with the labels that each got.

#468 feat: use starknet-react v2 & add custom transaction manager
  components/UI/modalProfilePic.tsx
  components/UI/modalWallet.tsx
  components/UI/navbar.tsx
  components/UI/wallets.tsx
  components/discount/registerDiscount.tsx
  components/domains/externalDomainActions.tsx
  components/domains/registerV2.tsx
  components/domains/renewal.tsx
  components/identities/actions/changeAddressModal.tsx
  components/identities/actions/clickable/clickablePersonhoodIcon.tsx
  components/identities/actions/identityActions.tsx
  components/identities/actions/renewalModal.tsx
  components/identities/actions/subdomainModal.tsx
  components/identities/actions/transferFormModal.tsx
  hooks/naming.ts
  hooks/useNotificationManager.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/discord.tsx
  pages/github.tsx
  pages/identities.tsx
  pages/twitter.tsx
  types/frontTypes.d.ts
  utils/constants.ts
Labels: 🔥 Ready for review

#479 feat: back button in identity page
  pages/identities/[tokenId].tsx
  styles/components/backButton.module.css
  styles/components/identitiesV1.module.css
Labels: 🔥 Ready for review

#465 MEP 30/10/2023
  .github/ISSUE_TEMPLATE/feature_request.md
  components/UI/iconsComponents/icons/animaIcon.tsx
  components/UI/iconsComponents/icons/doneFilledIcon.tsx
  components/UI/modalProfilePic.tsx
  components/UI/modalWallet.tsx
  components/UI/navbar.tsx
  components/UI/nftCard.tsx
  components/UI/registerConfirmationModal.tsx
  components/UI/wallets.tsx
  components/discount/registerDiscount.tsx
  components/domains/externalDomainActions.tsx
  components/domains/registerV2.tsx
  components/domains/renewal.tsx
  components/identities/actions/changeAddressModal.tsx
  components/identities/actions/clickable/clickablePersonhoodIcon.tsx
  components/identities/actions/identityActions.tsx
  components/identities/actions/renewalModal.tsx
  components/identities/actions/socialmediaActions.tsx
  components/identities/actions/subdomainModal.tsx
  components/identities/actions/transferFormModal.tsx
  components/identities/identitiesGalleryV1.tsx
  components/identities/identityCard.tsx
  components/identities/skeletons/pfpSkeleton.tsx
  components/identities/updateProfilePic.tsx
  context/StarknetIdJsProvider.tsx
  hooks/naming.ts
  hooks/useGetDiscoveryWallets.ts
  hooks/useNotificationManager.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/discord.tsx
  pages/github.tsx
  pages/identities.tsx
  pages/identities/[tokenId].tsx
  pages/search.tsx
  pages/twitter.tsx
  styles/components/backButton.module.css
  styles/components/icons.module.css
  styles/components/identitiesV1.module.css
  styles/components/identityCard.module.css
  styles/components/profilePic.module.css
  tests/utils/browserService.test.js
  tests/utils/feltService.test.js
  tests/utils/stringService.test.js
  types/backTypes.d.ts
  types/frontTypes.d.ts
  utils/browserService.ts
  utils/callData/identityChangeCalls.ts
  utils/constants.ts
  utils/feltService.ts
  utils/nftService.ts
  utils/stringService.ts
  utils/userDataService.ts
Labels: 🚧 In progress do not merge

#488 fixing expiry feedback notification
  components/identities/identityWarnings.tsx
Labels: 🔥 Ready for review

#490 feat: submenu dropdown
  components/UI/desktopNav.tsx
  components/UI/navbar.tsx
  styles/components/desktopNav.module.css
  styles/components/navbar.module.css
  styles/globals.css
Labels: 🔥 Ready for review

#497 fix: useNotificationManager
  hooks/useNotificationManager.ts
  package-lock.json
  package.json
  pages/_app.tsx
Labels: 🔥 Ready for review

#499 fix: hover of pfp
  components/UI/nftCard.tsx
  components/identities/identityCard.tsx
  components/identities/updateProfilePic.tsx
  tests/utils/debounceService.test.js
  utils/debounceService.ts
Labels: 🔥 Ready for review

#254 feat: add auto renewal button
  abi/starknet/renewal.sierra.json
  components/UI/textField.tsx
  components/domains/registerCheckboxes.tsx
  components/domains/registerV2.tsx
  components/domains/renewal.tsx
  components/domains/selectState.tsx
  components/domains/usForm.tsx
  components/identities/actions/autoRenewalModal.tsx
  components/identities/actions/identityActions.tsx
  hooks/contracts.ts
  package-lock.json
  pages/register/[domainToRegister].tsx
  pages/renewal.tsx
  public/visuals/starknetIdLongLogo.webp
  styles/components/autoRenewal.module.css
  styles/components/button.module.css
  styles/components/identityMenu.module.css
  styles/components/textField.module.css
  styles/components/variants.module.css
  utils/callData/autoRenewalCalls.ts
  utils/callData/registrationCalls.ts
  utils/constants.ts
Labels: ❌ Change request

#498 Ref: update pfp settings
  components/UI/iconsComponents/icons/arrowRightIcon.tsx
  components/identities/selectedCollections.tsx
  components/identities/updateProfilePic.tsx
  package-lock.json
  package.json
  styles/components/profilePic.module.css
  utils/constants.ts
Labels: 🔥 Ready for review

#502 fix: AR disable modal
  components/identities/actions/identityActions.tsx
Labels: 🔥 Ready for review

#501 ref: add swiss tax
  components/discount/registerDiscount.tsx
  components/domains/registerSummary.tsx
  components/domains/registerV2.tsx
  components/domains/renewal.tsx
  components/domains/swissForm.tsx
  components/identities/actions/autoRenewalModal.tsx
  components/identities/actions/clickable/clickablePersonhoodIcon.tsx
  package.json
  styles/components/variants.module.css
  tests/utils/priceService.test.js
  utils/constants.ts
  utils/priceService.ts
Labels: ❌ Change request

#505 fix: metadata hash ar problem
  .eslintrc.json
  components/UI/desktopNav.tsx
  components/UI/modalProfilePic.tsx
  components/UI/modalWallet.tsx
  components/UI/navbar.tsx
  components/UI/nftCard.tsx
  components/domains/registerV2.tsx
  components/domains/renewal.tsx
  components/identities/actions/autoRenewalModal.tsx
  package-lock.json
  package.json
  pages/identities.tsx
  utils/callData/registrationCalls.ts
  utils/feltService.ts
  utils/stringService.ts
  utils/userDataService.ts
Labels: ❌ Change request

#515 fix: tx history modal
  components/UI/modalWallet.tsx
  styles/components/walletMessage.module.css
Labels: 🔥 Ready for review

#520 fix: checkout bugs
  components/domains/registerV2.tsx
  components/domains/renewal.tsx
  components/domains/swissForm.tsx
Labels: 🔥 Ready for review

#524 fix: menu not working on mobile
  components/UI/navbar.tsx
Labels: 🔥 Ready for review, 🦾 Needs front-end review

#525 fix: style modal
  components/identities/actions/autoRenewalModal.tsx
  styles/components/autoRenewal.module.css
Labels: 🔥 Ready for review

#528 fix: back button impossible to see
  styles/components/profilePic.module.css
Labels: 🔥 Ready for review, 🦾 Needs front-end review

#529 fix: view more strange animation
  styles/components/identitiesV1.module.css
  styles/components/identityCard.module.css
Labels: 🔥 Ready for review, 🦾 Needs front-end review

#514 ref: remove useEffect Warnings
  components/UI/searchBar.tsx
  components/discount/registerDiscount.tsx
  components/domains/registerSummary.tsx
  components/domains/renewalDomainsBox.tsx
  components/identities/actions/changeAddressModal.tsx
  components/identities/actions/clickable/clickablePersonhoodIcon.tsx
  components/identities/actions/identityActions.tsx
  components/identities/actions/renewalModal.tsx
  components/identities/actions/subdomainModal.tsx
  components/identities/actions/transferFormModal.tsx
  components/identities/updateProfilePic.tsx
  context/StarknetIdJsProvider.tsx
  hooks/useNotificationManager.ts
  pages/discord.tsx
  pages/github.tsx
  pages/twitter.tsx
Labels: 🚧 In progress do not merge

#531 ref: fetch whitelisted nft contract addresses
  abi/starknet/nft_pp_verifier_abi.json
  components/identities/updateProfilePic.tsx
  context/StarknetIdJsProvider.tsx
  hooks/contracts.ts
  tests/utils/nftService.test.js
  utils/nftService.ts
Labels: 🔥 Ready for review

#537 feat: add pfp in navbar button
  components/UI/button.tsx
  components/UI/navbar.tsx
  components/domains/details.tsx
  hooks/naming.ts
  package-lock.json
  package.json
  styles/components/button.module.css
Labels: 🔥 Ready for review

#519 feat: add renew discount template
  abi/starknet/naming_abi.json
  components/discount/discountRenewalScreen.tsx
  components/discount/registerDiscount.tsx
  components/discount/renewalDiscount.tsx
  components/domains/freeRenewal.tsx
  components/domains/registerCheckboxes.tsx
  components/identities/actions/autoRenewalModal.tsx
  components/identities/actions/identityActions.tsx
  components/identities/actions/renewalModal.tsx
  pages/freerenewal.tsx
  public/freeRenewal/freeRenewal.webp
  utils/callData/autoRenewalCalls.ts
  utils/callData/registrationCalls.ts
  utils/discounts/freeRenewal.ts
Labels: 🔥 Ready for review
