Repository lfglabs-dev/app.starknet.id, pull requests merged in 2024-01, with the labels that each got.

#611 Fix/cairo2 profile
  components/UI/navbar.tsx
  context/StarknetIdJsProvider.tsx
  package-lock.json
  package.json
  pages/_app.tsx
Labels: 🔥 Ready for review

#609 ref: use getMetdata in renewal and register pages
  components/domains/freeRenewal.tsx
  components/domains/registerV2.tsx
  components/domains/renewal.tsx
  pages/_app.tsx
  utils/callData/registrationCalls.ts
Labels: ❌ Change request

#616 ref: add subscription tags on identities page
  components/UI/iconsComponents/icons/renewalIcon.tsx
  components/identities/identitiesGalleryV1.tsx
  components/identities/subscriptionTooltip.tsx
  pages/identities.tsx
  styles/components/identitiesV1.module.css
Labels: 🔥 Ready for review, 🦾 Needs front-end review

#620 fix: search bar
  components/UI/searchBar.tsx
Labels: 🔥 Ready for review

#619 ref: remove pfp from context
  components/UI/modalProfilePic.tsx
  components/identities/identitiesGalleryV1.tsx
  context/StarknetIdJsProvider.tsx
  pages/identities/[tokenId].tsx
  pages/search.tsx
  tests/utils/userDataService.test.js
  utils/apiWrappers/identity.ts
  utils/userDataService.ts
Labels: 🔥 Ready for review

#623 feat: improve checkout style
  components/domains/registerSummary.tsx
  styles/components/registerV2.module.css
Labels: 🔥 Ready for review, 🦾 Needs front-end review

#624 feat: new card animation by hovering
  components/identities/identitiesGalleryV1.tsx
  components/identities/selectedCollections.tsx
  styles/components/identitiesV1.module.css
  styles/components/profilePic.module.css
Labels: 🔥 Ready for review, 🦾 Needs front-end review

#633 fix: using new token id as main id when chosing old
  components/domains/registerV2.tsx
Labels: 🔥 Ready for review

#631 feat: pfp collections page
  components/UI/desktopNav.tsx
  components/UI/navbar.tsx
  components/pfpcollections/pfpNftCard.tsx
  pages/pfpcollections.tsx
  public/pfpCollections/starknetQuest.webp
  styles/components/pfpNftCard.module.css
  styles/pfpcollections.module.css
  utils/constants.ts
Labels: 🍾 Priority feature, 🔥 Ready for review

#569 Feat: sol domains frontend
  abi/starknet/naming_abi.json
  abi/starknet/sol_subdomain_abi.json
  components/UI/iconsComponents/icons/optionIcon.tsx
  components/UI/progressBar.tsx
  components/solana/changeAddressModal.tsx
  components/solana/domainActions.tsx
  hooks/contracts.ts
  hooks/useHasClaimSolSubdomain.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/solana.tsx
  public/visuals/affiliate.webp
  styles/components/progressbar.module.css
  styles/globals.css
  styles/solana.module.css
  types/frontTypes.d.ts
  utils/callData/solanaCalls.ts
  utils/constants.ts
Labels: ❌ Change request

#647 fix: searchbar
  abi/starknet/naming_Naming.contract_class.json
  abi/starknet/naming_abi.json
  components/UI/searchBar.tsx
  tests/utils/stringService.test.js
  utils/stringService.ts
Labels: 🔥 Ready for review

#649 fix: social verifications
  components/identities/actions/clickable/clickableDiscordIcon.tsx
  components/identities/actions/clickable/clickableGithubIcon.tsx
  pages/discord.tsx
  pages/github.tsx
  pages/twitter.tsx
Labels: 🔥 Ready for review

#652 ref: redirect after domain purchase
  components/domains/registerV2.tsx
Labels: 🔥 Ready for review

#645 feat: subscription tooltip
  components/UI/inputHelper.tsx
  components/UI/styledTooltip.tsx
  components/discount/renewalDiscount.tsx
  components/domains/registerCheckboxes.tsx
  components/domains/registerV2.tsx
  pages/freerenewal.tsx
Labels: 🔥 Ready for review
